### ISSUE TITLE
Handle Roblox API invalid name

### ISSUE THREAD

**Issue by OverHash** [Roblox/tarmac#26]
Repro: Upload a file named Panda Fox.png, with
```bash
tarmac upload-image images/image.png -- name "Panda Fox.png" -vvv
```

You will get an output similar to this: 
![image](https://user-images.githubusercontent.com/46231745/77499974-87d2d300-6eb8-11ea-8c3d-2d7c5a721a09.png)

Roblox is responding by telling Tarmac that the name is inappropriate, however, tarmac will immediately error, thus cancelling any work it has done

This is problematic as
* It is not a graceful way to handle the error
* All previous images uploaded must be reuploaded (very time consuming)

**Comment by LPGhatguy** [comment]
Fixed in 7581f5e459ad0f0c41d4281f75f5d31f25b98079.
