### ISSUE TITLE
Option to alpha bleed images

### ISSUE THREAD

**Issue by Kampfkarren** [Roblox/tarmac#29]
This might be out of scope for Tarmac, but there's never a case where I want an image with transparency uploaded but *not* alpha bled.

@Quenty released an article titled ["Fixing images in Roblox UI"](https://medium.com/roblox-development/fixing-images-in-roblox-ui-to-look-good-2e0a7880b1ec). In this article, he explains how due to a bug, images with transparency form ugly pixels around them. The solution is to change the RGB values of the alpha to coincide with the border. 

[XAXA released a tool for this that I use regularly](https://js.do/rootmars/alpha_bleed_js). It would be very useful if Tarmac could automate this process.

**Comment by Quenty** [comment]
I second this proposal, would love to see this. It's a primary aspect of managing assets on Roblox.

This would not to be configurable. We probably want to look at webpack to see how to best handle this configuration.

**Comment by LPGhatguy** [comment]
Tarmac currently does alpha bleed images that are packed into spritesheets. There's an open issue to extend this to all images: #20.

Going to close this as a duplicate, feel free to reopen if I missed something!
